export const NORMAL_KEYMAPS: Record<string, string> = {
  insert_before: "i",
  insert_start: "I",
  insert_after: "a",
  insert_end: "A",
  left: "h",
  down: "j",
  up: "k",
  right: "l",
  join_line: "J",
  // delete_line": "d d",
  insert_below: "o",
  insert_above: "O",
  paste_after: "p",
  paste_before: "P",
  cut_char: "x",
  cut_char_before: "X",
  undo: "u",
  redo: "ctrl+r",
};
