name: Chrome Extension PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  pr-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Determine action
        id: pr_action
        run: |
          if [ "${{ github.event.action }}" = "closed" ]; then
            echo "ACTION=close" >> $GITHUB_ENV
          else
            echo "ACTION=build" >> $GITHUB_ENV

      - name: Build Vite project and create ZIP
        if: env.ACTION == 'build'
        run: |
          mkdir -p pr-preview
          cp -r dist/* pr-preview/ || true
          cp manifest.json pr-preview/
          ZIP_NAME="pr-preview-${GITHUB_HEAD_REF}.zip"
          zip -r $ZIP_NAME pr-preview
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Deploy ZIP to GitHub Pages
        if: env.ACTION == 'build'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          mkdir -p pr-previews
          mv $ZIP_NAME pr-previews/
          git add pr-previews/$ZIP_NAME
          git commit -m "Add PR preview ZIP: $GITHUB_HEAD_REF" || echo "Nothing to commit"
          git push origin gh-pages --force

      - name: Add PR comment with download link
        if: env.ACTION == 'build'
        uses: actions/github-script@v7
        with:
          script: |
            const zipName = process.env.ZIP_NAME;
            const url = `https://${process.env.GITHUB_REPOSITORY_OWNER}.github.io/${process.env.GITHUB_REPOSITORY_NAME}/pr-previews/${zipName}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ PR用のChrome拡張プレビューがビルドされました！\n\n[ダウンロードはこちら](${url})`
            });

      - name: Remove ZIP on PR close
        if: env.ACTION == 'close'
        run: |
          ZIP_NAME="pr-preview-${GITHUB_HEAD_REF}.zip"
          echo "Removing ZIP: $ZIP_NAME from gh-pages"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin gh-pages
          git checkout gh-pages
          rm -f pr-previews/$ZIP_NAME
          git add pr-previews/$ZIP_NAME
          git commit -m "Remove PR preview ZIP: $GITHUB_HEAD_REF" || echo "Nothing to commit"
          git push origin gh-pages --force
