name: Vitest

on: 
  pull_request:

jobs:
  vitest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | BUN_VERSION="1.9.7" bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          bun --version
      - name: Install Deps
        run: bun install --frozen-lockfile
      - name: Test
        run: bun run test --coverage.enabled true
      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
